imports:
    - { resource: sulu.yml }
    - { resource: security.yml }
    - { resource: ../config.yml }
    - { resource: ../widgets.yml }

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]

sulu_route:
    mappings:
        Massive\Bundle\BlogBundle\Entity\BlogTranslation:
            route_schema: /{object.getTitle()}
